name: dbt Deploy DEV

on:
  push:
    branches:
      - développement

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Download previous manifest
        uses: actions/download-artifact@v3
        with:
          name: dbt-manifest-dev
          path: ./airbnb/target

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/développement'
        run: dbt run --profiles-dir ./airbnb --project-dir ./airbnb --target dev

      - name: Upload current manifest
        uses: actions/upload-artifact@v3
        with:
          name: dbt-manifest-dev
          path: ./airbnb/target/manifest.json