name: dbt Deploy DEV

on:
  push:
    branches:
      - développement

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Restore dbt manifest cache
        uses: actions/cache@v3
        with:
          path: ./airbnb/target
          key: dbt-manifest-${{ github.sha }}
          restore-keys: |
            dbt-manifest-

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/développement'
        run: dbt run --select state:modified+ --profiles-dir ./airbnb --project-dir ./airbnb --target dev

