name: dbt Deploy DEV

on:
  push:
    branches:
      - développement

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch manifest branch
        run: |
          git fetch origin ci-artifacts:ci-artifacts || git checkout --orphan ci-artifacts
          git checkout ci-artifacts || git checkout -b ci-artifacts
          mkdir -p ./prev_manifest
          if [ -f manifest.json ]; then
            cp manifest.json ./prev_manifest/manifest.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Check manifest
        id: manifest-check
        run: |
          if [ -f "./prev_manifest/manifest.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build only changed models - Deploy to DEV
        if: steps.manifest-check.outputs.exists == 'true' && github.ref == 'refs/heads/développement'
        run: dbt build --profiles-dir ./airbnb --project-dir ./airbnb --target dev --select state:modified+ --state ./prev_manifest

      - name: Build full project (no manifest available) - Deploy to DEV
        if: steps.manifest-check.outputs.exists == 'false' && github.ref == 'refs/heads/développement'
        run: dbt build --profiles-dir ./airbnb --project-dir ./airbnb --target dev --full-refresh

      - name: Save new manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cp ./airbnb/target/manifest.json ./manifest.json
          git add manifest.json
          git commit -m "Update dbt manifest for run ${{ github.run_id }}" || echo "No changes to commit"
          git push origin ci-artifacts
