name: dbt Deploy DEV

on:
  push:
    branches:
      - développement

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Download previous manifest
        uses: actions/download-artifact@v4
        continue-on-error: true 
        with:
          name: dbt-manifest-dev
          path: ./airbnb/target

      - name: Check manifest
        id: manifest-check
        run: |
          if [ -f "./prev_manifest/manifest.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build only changed models - Deploy to DEV
        if: steps.manifest-check.outputs.exists == 'true' && github.ref == 'refs/heads/développement'
        run: dbt build --profiles-dir ./airbnb --project-dir ./airbnb --target dev --select state:modified+ --state ./prev_manifest

      - name: Build full project (no manifest available) - Deploy to DEV
        if: steps.manifest-check.outputs.exists == 'false' && github.ref == 'refs/heads/développement'
        run: dbt build --profiles-dir ./airbnb --project-dir ./airbnb --target dev --full-refresh

      - name: Upload current manifest
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest-dev
          path: ./airbnb/target/manifest.json